In [10]:
#Load Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline  

In [11]:
#Load Dataset
dataset = pd.read_csv('./Mktg_Campaign.csv')
dataset.head()

Year_Birth   Education Marital_Status  Income  Kidhome  Teenhome  Recency  \
0        1957  Graduation         Single   58138        0         0       58   
1        1954  Graduation         Single   46344        1         1       38   
2        1965  Graduation       Together   71613        0         0       26   
3        1984  Graduation       Together   26646        1         0       26   
4        1981         PhD        Married   58293        1         0       94   

   MntWines  MntFruits  MntMeatProducts  ...  NumWebVisitsMonth  AcceptedCmp3  \
0       635         88              546  ...                  7             0   
1        11          1                6  ...                  5             0   
2       426         49              127  ...                  4             0   
3        11          4               20  ...                  6             0   
4       173         43              118  ...                  5             0   

   AcceptedCmp4  AcceptedCmp5  AcceptedCmp1  AcceptedCmp2  Complain  \
0             0             0             0             0         0   
1             0             0             0             0         0   
2             0             0             0             0         0   
3             0             0             0             0         0   
4             0             0             0             0         0   

   Z_CostContact  Z_Revenue  Response  
0              3         11         1  
1              3         11         0  
2              3         11         0  
3              3         11         0  
4              3         11         0  

[5 rows x 27 columns]

In [12]:
#Create copy of Dataset
dataset2=dataset

#Convert Object columns to numeric
dataset2 = pd.get_dummies(dataset2)
dataset2.head()

Year_Birth  Income  Kidhome  Teenhome  Recency  MntWines  MntFruits  \
0        1957   58138        0         0       58       635         88   
1        1954   46344        1         1       38        11          1   
2        1965   71613        0         0       26       426         49   
3        1984   26646        1         0       26        11          4   
4        1981   58293        1         0       94       173         43   

   MntMeatProducts  MntFishProducts  MntSweetProducts  ...  Education_Master  \
0              546              172                88  ...             False   
1                6                2                 1  ...             False   
2              127              111                21  ...             False   
3               20               10                 3  ...             False   
4              118               46                27  ...             False   

   Education_PhD  Marital_Status_Absurd  Marital_Status_Alone  \
0          False                  False                 False   
1          False                  False                 False   
2          False                  False                 False   
3          False                  False                 False   
4           True                  False                 False   

   Marital_Status_Divorced  Marital_Status_Married  Marital_Status_Single  \
0                    False                   False                   True   
1                    False                   False                   True   
2                    False                   False                  False   
3                    False                   False                  False   
4                    False                    True                  False   

   Marital_Status_Together  Marital_Status_Widow  Marital_Status_YOLO  
0                    False                 False                False  
1                    False                 False                False  
2                     True                 False                False  
3                     True                 False                False  
4                    False                 False                False  

[5 rows x 38 columns]

In [15]:
#Create x and y variables
x = dataset2.drop('Response', axis=1).to_numpy()
y = dataset2['Response'].to_numpy()

#Create x and y datasets
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x, y, test_size = 0.20, stratify=y, random_state = 100)

#Scale Data
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train2 = sc.fit_transform(x_train)
x_test2 = sc.transform(x_test)

In [16]:
#Create Response Model
from sklearn.metrics import classification_report, confusion_matrix  
from sklearn.tree import DecisionTreeClassifier  

for name,method in [('DT', DecisionTreeClassifier(random_state=100))]: 
    method.fit(x_train2,y_train)
    predict = method.predict(x_test2)
    print('\nEstimator: {}'.format(name)) 
    print(confusion_matrix(y_test,predict))  
    print(classification_report(y_test,predict)) 


Estimator: DT
[[351  26]
 [ 32  35]]
              precision    recall  f1-score   support

           0       0.92      0.93      0.92       377
           1       0.57      0.52      0.55        67

    accuracy                           0.87       444
   macro avg       0.75      0.73      0.74       444
weighted avg       0.86      0.87      0.87       444



In [44]:
#Script for SVM and NB
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import classification_report, confusion_matrix  

for name,method in [('SVM', SVC(random_state=100)),
                    ('Naive Bayes',GaussianNB())]: 
    method.fit(x_train2,y_train)
    predict = method.predict(x_test2)
    target_names=['0','1']
    print('\nEstimator: {}'.format(name)) 
    print(confusion_matrix(y_test,predict))  
    print(classification_report(y_test,predict,target_names=target_names))


Estimator: SVM
[[366  11]
 [ 50  17]]
              precision    recall  f1-score   support

           0       0.88      0.97      0.92       377
           1       0.61      0.25      0.36        67

    accuracy                           0.86       444
   macro avg       0.74      0.61      0.64       444
weighted avg       0.84      0.86      0.84       444


Estimator: Naive Bayes
[[334  43]
 [ 40  27]]
              precision    recall  f1-score   support

           0       0.89      0.89      0.89       377
           1       0.39      0.40      0.39        67

    accuracy                           0.81       444
   macro avg       0.64      0.64      0.64       444
weighted avg       0.82      0.81      0.81       444



In [45]:
print(np.unique(y_test))

[0 1]
